nb_threads         = 80
parts_file         = ./data/pieces.csv
expand_level       = 7
expand_max_stock   = 100000000
expand_max_levels  = 10
http_port          = 8082
http_token_file    = /Users/xaviergriffon/eternityii_token
stock_files        = 40
stock_spill_dir    = ./eternityii-spill
rebalance_budget   = 10000
tcp_timeout        = 10
auto_roles         = 1
stop_on_solution   = 0
headless           = 0
